### ISSUE TITLE
Static or interactive plots?

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/Hackathon-Central-2019#3]
What are the relative costs and benefits to static or interactive plots?

**Comment by wetlandscapes** [comment]
Perhaps obvious, but I think it will depend on the framework used. I use ggplot a lot. When combined with `plotly::ggplotly` the costs are negligible. That said, I've not tried to build something like that into a ShinyApp, so don't know how well all of those different JavaScript tools would work together.

**Comment by jhp7e** [comment]
The main advantage of static plots is speed. Interactive plots with lots of points can be quite slow to render (at least based on my DYGraphs experience).  I'm less experienced with Shiny so I can't comment on its speed. 

I would say that the intended use is also relevant.... some users (I'll call them "lazy" users) just want some graphs to look at.  Other users (I'll call them "eager" users) want to burrow in to some specific aspect of the data.  I'd say static graphs are better for the "lazy" user and interactive plots are better for the "eager" user.

**Comment by lkuiucsb** [comment]
I agree with @jhp7e from a programmer's perspective. From an end-user perspective, after the code has been developed, the interactive plot is to use on data exploration, and it is a quick and easy way to scan through all the possible figures. The static plot is for producing final figures (e.g. a user want to look into the detail of the plotting code), by tweaking the parameters and adding some complicated expressions into the figures. 

The code for a static figure is easier to manipulate. The code editing for any particular figure (e.g. time on the x-axis needs to be displayed by week instead of by day) will be not likely to apply to other figures generated using the interactive plot.

**Comment by clnsmth** [comment]
We decided to do both static and interactive plotting.
